### ISSUE TITLE
pipe_connect_to_file, ipc_send_recv_pipe, fs_readdir_file, dlerror - test failures on Windows

### ISSUE THREAD

**Issue by ionut-rosoiu** [joyent/libuv#376]
Windows Server 2008 R2, VS2010

```
[%   0|+   2|-   0]: pipe_connect_to_file
`pipe_connect_to_file` failed: exit code 3
Output from process `pipe_connect_to_file`:
Assertion failed in test\test-pipe-connect-error.c on line 56: uv_last_error(uv_default_loop()).code == UV_ENOTSOCK || uv_last_error(uv_default_loop()
).code == UV_ECONNREFUSED
=============================================================
[%   0|+   6|-   1]: ipc_send_recv_pipe
`ipc_send_recv_pipe` failed: exit code 3
Output from process `ipc_send_recv_pipe`:
Assertion failed in test\test-ipc-send-recv.c on line 101: r == 0
Assertion failed in test\test-ipc-send-recv.c on line 160: pending == UV_NAMED_PIPE || pending == UV_TCP
=============================================================
[%   0|+  34|-   2]: udp_options
`udp_options` failed: exit code 3
Output from process `udp_options`:
Assertion failed in test\test-udp-options.c on line 60: r == -1
=============================================================
[%   0|+  90|-   3]: spawn_and_kill_with_std
`spawn_and_kill_with_std` failed: timeout
Output from process `spawn_and_kill_with_std`:
close_cb
exit_cb
close_cb
=============================================================
[%   0|+ 122|-   4]: fs_readdir_file
`fs_readdir_file` failed: exit code 3
Output from process `fs_readdir_file`:
Assertion failed in test\test-fs.c on line 1500: uv_last_error(loop).code == UV_ENOTDIR
=============================================================
[%   0|+ 133|-   5]: dlerror
`dlerror` failed: exit code 3
Output from process `dlerror`:
Assertion failed in test\test-dlerror.c on line 46: strstr(msg, dlerror_desc) != NULL
```

**Comment by piscisaureus** [comment]
These should have been fixed now.

**Comment by saghul** [comment]
I'm still getting some of those myself (libuv on Windows 7 32 bit using MinGW):

```
=============================================================
[%   0|+   7|-   0]: ipc_send_recv_tcp
`ipc_send_recv_tcp` failed: exit code 3
Output from process `ipc_send_recv_tcp`:
Assertion failed in test/test-ipc-send-recv.c on line 160: pending == UV_NAMED_P
IPE || pending == UV_TCP

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
exit_cb
Assertion failed in test/test-ipc.c on line 90: exit_status == 0

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
=============================================================
[%   0|+ 102|-   1]: fs_file_loop
`fs_file_loop` failed: exit code 3
Output from process `fs_file_loop`:
Assertion failed in test/test-fs.c on line 521: uv_last_error(loop).code == UV_E
LOOP

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
=============================================================
[%   0|+ 128|-   2]: eio_overflow
`eio_overflow` failed: exit code 3
Output from process `eio_overflow`:
Assertion failed in test/test-eio-overflow.c on line 61: opened - closed < max_d
elta

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
=============================================================
[% 100|+ 135|-   3]: Done.
make: *** [test] Error 3
```

I also got this on on another run:

```
=============================================================
[%   0|+  76|-   0]: async
`async` failed: exit code 3
Output from process `async`:
async1_cb #1
async1_cb #2
async1_cb #3
Assertion failed: !(handle->flags & UV_HANDLE_CLOSING), file src/win/async.c, li
ne 105

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
=============================================================
```

**Comment by piscisaureus** [comment]
@saghul I just checked it with the latest master, all tests pass fine for me using mingw32. Are you sure you updated to the latest master?

The async test could in theory fail due to a race condition, although that never really happens for me.

**Comment by saghul** [comment]
I'll test again as soon as I get back home, I don't have a Windows
machine with me ;-)

/Saúl

On 13/04/2012, at 16:53, Bert Belder
reply@reply.github.com
wrote:

**Comment by saghul** [comment]
I just repeated the tests (3 times) after a fresh checkout and here is what I got:

```
- ipc_send_recv_tcp failed 2 out of 3 times
- fs_file_loop failed 3 out of 3 times
- eio_overflow failures seem quite random
- async fails 1 out of 3 times on my machine (it's a VM, Win7 32 bits)
```

**Comment by bnoordhuis** [comment]
eio_overflow is not a great test, it's timing sensitive. The other tests should not fail. async in particular is odd, it never fails on Unices.

**Comment by saghul** [comment]
I run another 3-runs of the test suite after I saw the changes to the async test. That seems fixed, but now I get these:

```
=============================================================
[%   0|+   5|-   0]: ipc_listen_before_write
`ipc_listen_before_write` failed: timeout
Output from process `ipc_listen_before_write`:
got 6 bytes
got 20 bytes
exit_cb
=============================================================
[%   0|+  41|-   1]: connection_fail
`connection_fail` failed: timeout
Output from process `connection_fail`: (no output)
=============================================================
[%   0|+  41|-   2]: connection_fail_doesnt_auto_close
`connection_fail_doesnt_auto_close` failed: timeout
Output from process `connection_fail_doesnt_auto_close`: (no output)
=============================================================
[%   0|+ 100|-   3]: fs_file_loop
`fs_file_loop` failed: exit code 3
Output from process `fs_file_loop`:
Assertion failed in test/test-fs.c on line 521: uv_last_error(loop).code == UV_E
LOOP

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
=============================================================
[%   0|+ 126|-   4]: eio_overflow
`eio_overflow` failed: exit code 3
Output from process `eio_overflow`:
Assertion failed in test/test-eio-overflow.c on line 61: opened - closed < max_d
elta

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
=============================================================
[% 100|+ 133|-   5]: Done.
```

The ipc_listen_before _write test failures are now consistent, it fails all the time for me, so does the fs_file_loop.

Can this issue be reopened please? :-)
