### ISSUE TITLE
uv_close(TCP handle) does not immediately invoke uv_connect_cb(EINTR)

### ISSUE THREAD

**Issue by ibc** [joyent/libuv#448]
(Linux libuv master branch). Pseudo-code:

<pre>
# A TCP socket that will be in connecting state for long...
uv_tcp_init(loop, tcp_handle);
uv_tcp_connect(tcp_handle, "1.2.3.4", 9999);
uv_read_start(tcp_handle);

# Run a timer that invokes uv_close(tcp_handle) after two seconds.
[...]

# We expect that uv_connect_cb(EINTR) should happen right now, but that
# does not happen.

# It will happen in next event of the loop (if there are...), so for example if we
# run another timer to fire in 5 seconds (and do nothing in the callback) then
# the uv_close_cb(tcp_handle) is called after 5 seconds and thus the
# on_connect_cb(EINTR).

uv_run(loop);
</pre>

Maybe related to #447?

**Comment by ibc** [comment]
**NOTE:**  It's a regression, it worked fine in a copy of libuv from 2012-05-29 I had somewhere...

**Comment by bnoordhuis** [comment]
Cannot reproduce, same for #447. Can you post a test case? I just wasted the better part of an hour trying to come up with one based on your description...

**Comment by bnoordhuis** [comment]
That said, I'm pretty sure I fixed the issues you mention in 649ad50.

**Comment by ibc** [comment]
Hi, I still reproduce this issue after the commit. Let me post a test case.

**Comment by ibc** [comment]
Hi, working code that demonstrates the bug:  https://gist.github.com/2880865

**Comment by bnoordhuis** [comment]
Fixed in dea4594.

**Comment by ibc** [comment]
Just two lines of code???? XD

Thanks a lot, tested in my code and works.
